services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    volumes:
      - type: bind
        source: /home/chkpe/rustdesk/config
        target: /root
        bind:
          create_host_path: true
    network_mode: "host"

    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - type: bind
        source: /home/chkpe/rustdesk/config
        target: /root
        bind:
          create_host_path: true
    network_mode: "host"
    restart: unless-stopped
